apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: data
      protocol: TCP
      port: 20
    - name: cmd
      protocol: TCP
      port: 21
    - name: pasv
      protocol: TCP
      port: 42000
    - name: pasv1
      protocol: TCP
      port: 42001
    - name: pasv2
      protocol: TCP
      port: 42002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 42000
            - containerPort: 42001
            - containerPort: 42002